Separate contribution workflow information into two parts #120
eclipse-platform/.github pull request #135
Opened 2023-07-04 15:37 UTC by HeikoKlare

This is a proposal for addressing https://github.com/eclipse-platform/.github/issues/120#issuecomment-1517443447 and https://github.com/eclipse-platform/.github/issues/120#issuecomment-1517448655.

The `CONTRIBUTING.md` describes the contribution workflow combining the information for how to set up and manage a fork and for how to create and process a pull request.

This change separates the two parts of the contribution process into separate sections. In addition, is extends the explanation of how to manage the local clone for a fork by an alternative workflow of having the main Eclipse repository as the origin remote.

To conform to recent repository merges, the change also clean ups the list of repositories in the Eclipse platform organization.

Contributes to https://github.com/eclipse-platform/.github/issues/120

2023-07-04 15:45 UTC, merks commented
It’s a good idea!

2023-07-06 14:35 UTC, HeikoKlare commented
@BeckerWdf Since you liked the idea (https://github.com/eclipse-platform/.github/issues/120#issuecomment-1517448655) and updated the description before, it would be great to also have your feedback on this 🙂

2023-07-10 07:26 UTC, BeckerWdf requested changes

2023-07-10 07:26 UTC, BeckerWdf commented on CONTRIBUTING.md
> +9. Reviewers can review the pull request on the GitHub website or fetch the PR using the menu _Fetch GitHub PR_ in egit.
```suggestion
9. Reviewers can review the pull request on the GitHub website or fetch the PR using the _Fetch GitHub PR_ menu entry in the _Git Repositories_ view inside the Eclipse IDE.
```

2023-07-10 09:44 UTC, BeckerWdf approved these changes

2023-07-10 10:06 UTC, merged